spring.application.name=mini-instagram

spring.datasource.url=mini_instagramdb
spring.datasource.username=mini_instagramdb_user
spring.datasource.password=NmsZuAG6ki2pC60sbHEJkjiRJaFENR7Y
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=18000000

upload.path=uploads/posts
app.base-url=${APP_BASE_URL}
